services:
  configserver:
    image: config:latest
    container_name: configserver-ms
    ports:
      - "8071:8071"
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: eurekaserver:latest
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      - configserver
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: accounts:latest
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    depends_on:
      - configserver
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      LOANS_SERVICE_URL: "http://loans:8090"
      CARDS_SERVICE_URL: "http://cards:9000"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: loans:latest
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    depends_on:
      - configserver
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: cards:latest
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
    depends_on:
      - configserver
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  bank:
    driver: "bridge"